21-rails-review/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :bloggers, only: [:new, :show, :create]
  resources :posts, only: [:show, :create, :new, :edit, :update]
  resources :destination, only: [:show]

  patch '/posts/:id/add_likes', to: 'posts#add_likes', as:'add_likes'

end

21-rails-review/app/models/blogger.rb
class Blogger < ApplicationRecord
    has_many :posts
    has_many :destinations, through: :posts

    validates_uniqueness_of :name
    validates :age, numericality: {greater_than: 0}
    validates :bio, length: {minimum: 30} 
end

21-rails-review/app/models/destination.rb
class Destination < ApplicationRecord
    has_many :posts
    has_many :bloggers, through: :posts
end

21-rails-review/app/models/post.rb
class Post < ApplicationRecord
    belongs_to :blogger
    belongs_to :destination

    validates_presence_of :title
    validates :content, length: {minimum: 100} 

end

21-rails-review/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

21-rails-review/app/controllers/bloggers_controller.rb
class BloggersController < ApplicationController
    def show
        @blogger = Blogger.find(params[:id])
        @likes = @blogger.posts.sum{|post|post.likes}
        @featured = @blogger.posts.max{|p| p.likes }
        
        #@likes = @blogger.posts.sum(:likes)
    end 
end

21-rails-review/app/controllers/destination_controller.rb
class DestinationController < ApplicationController
    def show
        @destination = Destination.find(params[:id])
        @posts = @destination.posts.last(5)
        @featured = @destination.posts.max{|p| p.likes }
        @ave_age = @destination.bloggers.sum{|b| b.age}/@destination.bloggers.length
    end 
end

21-rails-review/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:show, :edit, :update, :add_likes]
    def new
        @post = Post.new
        @bloggers = Blogger.all 
        @destinations = Destination.all
    end 

    def show
    end 
    
    def create
        @post = Post.new(post_params)
        @post.likes = 0
        @post.save
        redirect_to @post 
    end 

    def edit
    end 

    def update
    end 

    def add_likes
        # @post.likes += 1
        # @post.save 
        @post.update(likes: @post.likes+1)
        redirect_to @post 
    end 

    private

    def find_post
        @post = Post.find(params[:id])
    end 

    def post_params
        params.require(:post).permit(:title, :content, :blogger_id, :destination_id)
    end 
end

21-rails-review/app/helpers/bloggers_helper.rb
module BloggersHelper
end

21-rails-review/app/helpers/destination_helper.rb
module DestinationHelper
end

21-rails-review/app/helpers/posts_helper.rb
module PostsHelper
end

21-rails-review/app/views/destination/show.erb
<h2><%= @destination.name%></h2>
<br>
<h2><%= @destination.country%></h2>
<h2>Average Age<%= @ave_age%></h2>
<h2>Featured Post: <%= link_to @featured.title, @featured %></h2>

<% @posts.each do |p| %>
    <div>
    <h3><%= p.title %></h3>
    <p><%= p.content %></p>
    </div>
<% end %>

21-rails-review/app/views/posts/_form.erb
<%= form_for @post do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title%>

    <%= f.label :content %>
    <%= f.text_area :content%>

    <%= f.collection_select :blogger_id, @bloggers, :id, :name%>
    <%= f.collection_select :destination_id, @destinations, :id, :name%>

    <%= f.submit %>

<% end %>
   

21-rails-review/app/views/posts/new.erb
<%= render "form"%>

21-rails-review/app/views/posts/show.erb
<h2><%= @post.title %></h2>
<p><%= @post.content%></p>
<p><%= @post.likes%></p>

<%= link_to @post.blogger.name, @post.blogger %>
<%= link_to @post.destination.name, @post.destination %>

<%= button_to "Like", add_likes_path, :method => :patch  %>