25-authorization/trivia/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resources :responses

  resources :log_in, only: [:new, :create]
  delete "logout", to: "log_in#destroy", as: "log_out"

  get :'random-question', to: 'responses#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

25-authorization/trivia/app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :question
    has_many :responses
end

25-authorization/trivia/app/models/question.rb
class Question < ApplicationRecord
    has_many :responses
    has_many :answers
    belongs_to :correct_answer, class_name: "Answer", optional: true

    def random_answers
        self.answers.order("RANDOM()")
    end
end

25-authorization/trivia/app/models/response.rb
class Response < ApplicationRecord
    belongs_to :question
    belongs_to :answer
    belongs_to :user
end

25-authorization/trivia/app/models/user.rb
class User < ApplicationRecord
    has_many :responses
    has_secure_password

    # def password=(value)
    #     self.password_digest == BCrypt::Password.create(value)
    # end 

    # def authenticate(password)
    #     BCrypt::Password.new(self.password_digest) == password
    # end 

end

25-authorization/trivia/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :fetch_user
    before_action :require_login

    def fetch_user
        @logged_in = logged_in?
        @user = User.find(current_user_id) if logged_in?
    end 

    def require_login
        unless logged_in?
            redirect_to new_log_in_path
        end 
    end 

    private

    def log_in_user(user_id)
        session[:user_id] = user_id
    end 

    def current_user_id
        session[:user_id]
    end 

    def logged_in?
        !!current_user_id
    end 

    def log_out_user
        session.delete(:user_id)
        flash[:errors]  = ["User logged out"]
        redirect_to new_log_in_path
    end 
end

25-authorization/trivia/app/controllers/log_in_controller.rb
class LogInController < ApplicationController
     skip_before_action :require_login,  :only => [:create, :new]
    def new
    end 

    def create
            @user = User.find_by(username:params[:log_in][:username])
            if @user && @user.authenticate(params[:log_in][:password])
                log_in_user(@user.id)
                redirect_to new_response_path
            else 
                
                flash[:errors] = ["Invalid Emial or Password"]
                redirect_to new_log_in_path
            end 

    end 

    def destroy
        log_out_user
    end 
end

25-authorization/trivia/app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
    before_action :define_question, :define_response

    def new
    end

    def define_question
        @number_correct = cookies["number_correct"]
        @question = Question.order("RANDOM()").limit(1)[0]

    end

    def define_response
        @questionResponse = Response.new({ question: @question })
    end

    def create
        if !cookies["number_correct"] 
            cookies["number_correct"] ||= 0
        end 
        byebug
        response = Response.create(response_params)

        if response.question.correct_answer == response.answer

            cookies["number_correct"] = cookies["number_correct"].to_i + 1
            
            puts "Correct"
        else

            puts "Incorrect"
        end
        redirect_to '/random-question'
        
    end

    def response_params
        params.require(:response).permit(:answer_id, :question_id).with_defaults(user_id: session[:user_id])
    end
end

25-authorization/trivia/app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :require_login,  :only => [:create, :new]

    def new
        @user = User.new 
    end 

    def create 
        
        @user = User.create(user_params)
        log_in_user(@user.id)

        if @user.valid?
            redirect_to new_response_path
        else
            redirect_to user_new 
        end
    end 

    private

    def user_params
        params.require(:user).permit(:username, :password)
    end 

end

25-authorization/trivia/app/helpers/answers_helper.rb
module AnswersHelper
end

25-authorization/trivia/app/helpers/application_helper.rb
module ApplicationHelper
end

25-authorization/trivia/app/helpers/log_in_helper.rb
module LogInHelper
end

25-authorization/trivia/app/helpers/questions_helper.rb
module QuestionsHelper
end

25-authorization/trivia/app/helpers/responses_helper.rb
module ResponsesHelper
end

25-authorization/trivia/app/helpers/users_helper.rb
module UsersHelper
end

25-authorization/trivia/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trivia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@100&display=swap" rel="stylesheet">

  </head>

  <body>

    <%  if @logged_in %>
    <h1> <%= @user.username %> </h1>
    <nav>
    <%= link_to "Log out", log_out_path,  :method => :delete %>
    <% else %>
    <nav>
      <%= link_to "Log in",  new_log_in_path %>
      <%= link_to "Sing up",  new_user_path %>
    <% end %>
  </nav>
  <% if flash[:errors]  %>
    <% flash[:errors].each do |error| %>
      <%= error %>
    <% end %>
  <% end %>
    <%= yield %>
  </body>
</html>

25-authorization/trivia/app/views/users/index.erb
<h1> Welcome userrname </h1>

25-authorization/trivia/app/views/users/new.erb
<div class="container" id="log_in_form" >
    <h2> Hi New User! </h1>
    <%= form_with model: @user  do |f|%>
        <%= f.label :username %>
        <%= f.text_field :username %>

        <%= f.label :password %>
        <%= f.text_field :password %>
        <%= f.submit %>
    <% end %>
</div>