18-many-to-many/art/config/routes.rb
Rails.application.routes.draw do
  resources :galleries, only: [:index, :show]
  resources :paintings
  resources :artists, only: [:index, :show, :edit, :update, :new, :create,]

  # get "/artists", to:"artists#index"
  get "rose", to:"artists#rose", as:"rose"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

18-many-to-many/art/app/models/artist.rb
class Artist < ApplicationRecord
    has_many :paintings, dependent: :destroy
    
    validates_presence_of :name
    validates_uniqueness_of :name

    validates :age, numericality: { greater_than: 0 }


end

18-many-to-many/art/app/models/contract.rb
class Contract < ApplicationRecord
    belongs_to :curator
    belongs_to :gallery
  end
  

18-many-to-many/art/app/models/curator.rb
class Curator < ApplicationRecord
    has_many :contracts, dependent: :destroy
    has_many :galleries, through: :contracts
  end
  

18-many-to-many/art/app/models/gallery.rb
class Gallery < ApplicationRecord
    has_many :paintings, dependent: :destroy

    has_many :contracts, dependent: :destroy
    has_many :curators, through: :contracts
end

18-many-to-many/art/app/models/painting.rb
class Painting < ApplicationRecord
  belongs_to :artist
  belongs_to :gallery
end

18-many-to-many/art/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
    def index 
        @artists = Artist.all
    end 

    def show
        @artist = Artist.find(params[:id])
    end 

    def new
        @artist = Artist.new
    end 

    def create
        @artist = Artist.create(artist_params)
        redirect_to @artist
    end 


    def edit
        @artist = Artist.find(params[:id])
    end 

    def update
        @artist = Artist.find(params[:id])
        # @artist.update(artist_params)
        if @artist.update(artist_params).valid?
            redirect_to @artist
        else 
            flash[:errors] = @artist.errors.full_messages
            redirect_to edit_artist_path
        end 
    end 

    def rose
    end 

    private 

    def artist_params 
        params.require(:artist).permit(:name, :death, :nationality, :known_for, :age)
    end 

end

18-many-to-many/art/app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
end

18-many-to-many/art/app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  before_action :set_painting, only: [:show, :edit, :update, :destroy]

  def index
    @paintings = Painting.all
  end
 
  def show
  end

  def new
    @painting = Painting.new
    @artists = Artist.all
    @galleries = Gallery.all
  end

  def edit
  end

  def create
    byebug
    @painting = Painting.create(painting_params)
    redirect_to @painting
  end

  def update
    @artists = Artist.all
  end


  def destroy
 
    @painting.destroy
    redirect_to paintings_path
  end

  private

  def set_painting
    @painting = Painting.find(params[:id])
  end 
 
  def painting_params
    params.require(:painting).permit(:name, :image, :artist_id, :gallery_id)
  end
end

18-many-to-many/art/app/helpers/artist_helper.rb
module ArtistHelper
end

18-many-to-many/art/app/helpers/galleries_helper.rb
module GalleriesHelper
end

18-many-to-many/art/app/helpers/paintings_helper.rb
module PaintingsHelper
end

18-many-to-many/art/app/views/artists/_form.erb
<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
        <p><%= error%> </p>
    <%end%>
<%end %>

<%= form_with model:@artist do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :death %>
    <%= f.text_field :death %>

    <%= f.label :nationality %>
    <%= f.text_field :nationality %>

    <%= f.label :known_for %>
    <%= f.text_field :known_for %>

    <%= f.label :age %>
    <%= f.text_field :age %>

    <%= f.submit%>
<% end %>

18-many-to-many/art/app/views/artists/edit.erb
<%# <form action="/artists/<%@artist.id% method="post">
    <input type="hidden" value="PATCH" name="_method">
    <label for="artist_name">Name</label>
    <input id="artist_name" type="text" name="name">

    <label for="artist_death">Death</label>
    <input id="artist_death" type="text" name="death">

    <label for="artist_nationality">Nationality</label>
    <input id="artist_nationality" type="text" name="nationality">

    <label for="artist_known_for">Known for</label>
    <input id="artist_known_for" type="text" name="known_for">


    <label for="artist_age">Age</label>
    <input id="artist_age" type="number" name="age"> 

    <input type="submit">
</form> %>

<%#= form_tag artist_path(@artist), method:"PATCH" do %>
    <%#= label_tag :name %>
    <%#= text_field_tag :name, @artist.name %>

    <%#= label_tag :death %>
    <%#= text_field_tag :death, @artist.death %>

    <%#= label_tag :nationality %>
    <%#= text_field_tag :nationality, @artist.nationality %>

    <%#= label_tag :known_for %>
    <%#= text_field_tag :known_for, @artist.known_for %>

    <%#= label_tag :age %>
    <%#= text_field_tag :age, @artist.age %>

    <%#= submit_tag %>
<%# end %>

<%= render "form" %>

18-many-to-many/art/app/views/artists/index.erb
 <% @artists.each do |artist| %>
   <%# <%= link_to artist.name, "/artists/#{artist.id}"%> 
   <%#= link_to artist.name, artist_path(artist) %>
   <%= link_to artist.name, artist %>

 <%end%>
<br>

   <%= link_to "Rose", rose_path %>

18-many-to-many/art/app/views/artists/rose.erb
<h1>🐱  Rose 🐱</h1>

18-many-to-many/art/app/views/artists/show.erb
<div><%= @artist.name %></div>
<div><%= @artist.death %></div>
<div><%= @artist.nationality %></div>
<div><%= @artist.known_for %></div>
<div><%= @artist.age %></div>

18-many-to-many/art/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Art</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>